### ISSUE TITLE
Interaction Glitch

### ISSUE THREAD

**Issue by thicksunny** [BreathTakinglyBinary/libDynamicForms#2]
After testing and playing around with this virion, I learned that if you interact with an item that will open a form, via right click on block, multiple windows will open, therefore causing you to have to manually exit them. My suggestion is to make it so if multiple are opened at once, simply just take the latest one, and discard the others.

**Comment by Xenophilicy** [comment]
@HyperFlareMC This isn't an issue with the library but an issue with your way of sending the form to a player. You can simply create a "cooldown" for the interact event so that the player can only open one at a time after several interaction events are called.

Using `time()` is your best bet for performance (rather than using a delayed/repeating task 🤮):
```php
private static $formInteract;
```
```php
$cooldown = 1; // seconds
if(isset(self::$formInteract[$player->getName()]) && self::$formInteract[$player->getName()] + $cooldown > time()) return;
self::$formInteract[$player->getName()] = time();
// send form
```

This will make sure that the player can only receive one form in a 1 second period of interaction events. Of course if you didn't want that extra isset garbage, you could just add the player's name on join (but be careful because reloads will mess that up).
